# Site settings
title: haviet template
admin-email: nikenhn@gmail.com
description: "Template này sử dụng Foundation Framework. Dựng bởi Nikenh."
baseurl: "/static-on-foundation"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
